- name: "Ansible para configurar VM"
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest
      
    - name: Verifique se uma lista de pacotes para instalar
      package:
        name: "{{ packages }}"
        state: present
        autoclean: yes
        autoremove: yes
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - lvm2
        - software-properties-common
        - ntpdate
        - openjdk-8-jdk

    - name: Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - boto
        - boto3
        - botocore
        - awscli
  