- name: "Ansible para configurar VM"
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest

    - name: Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - ansible
    
    - name: Download required roles docker (desktop local)
      local_action: command ansible-galaxy install nickjj.docker
      become: false

    - name: Download required roles java
      local_action: command ansible-galaxy install geerlingguy.java 
      become: false

    - name: Download required roles jenkins
      local_action: command ansible-galaxy install geerlingguy.jenkins 
      become: false
