- name: "Ansible para configurar VM"
  hosts: aws_ec2
  become: true
  gather_facts: yes

  tasks:
    - name: Linux - Atualizando todos os pacotes
      package:
        name: '*'
        state: latest

    - name: Repositorio Ansible
      apt_repository:
        repo: ppa:ansible/ansible
      
    - name: Verifique se uma lista de pacotes para instalar
      package:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - lvm2
        - software-properties-common
        - ntpdate

    - name: Verifica pacotes essenciais do python
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - boto
        - boto3
        - botocore
        - ansible
        - awscli
    
